development:
  adapter: postgresql
  database: paperquest_development
  pool: 5
  timeout: 5000
  username: postgres
  password: '111213'

test:
  adapter: postgresql
  database: paperquest_test
  pool: 5
  timeout: 5000
  username: postgres
  password: '111213'

production:
  adapter: postgresql
  database: paperquest_production
  pool: 5
  timeout: 5000